import 'package:flutter/material.dart';
const kPrimaryColor = Color(0xFFA3916B);
const kSecondaryColor = Color(0xFF294C46);
const imgPath = 'https://beta.aminyoussef.com/upload/';
const signInApi = 'https://beta.aminyoussef.com/api/api-login.php';
const signUpApi = 'https://beta.aminyoussef.com/api/api-sing-up.php';
const getAllLessonsApi = 'https://beta.aminyoussef.com/api/api-selectData.php?tableName=videos&where=sub&equalWhat=';
const getAllTeachersApi = 'https://beta.aminyoussef.com/api/api-selectData.php?tableName=users&where=rank&equalWhat=2';
const getTeacherByCourseApi = 'https://beta.aminyoussef.com/api/api-selectData.php?tableName=users&where=id&equalWhat=';
const getCourseByCode = 'https://beta.aminyoussef.com/api/api-code.php';
const getOwnedCourses = 'https://beta.aminyoussef.com/api/api-getOwnedCourse.php';
const getAllYearsApi = 'https://beta.aminyoussef.com/api/api-selectData.php?tableName=class&where=NULL&equalWhat=NULL';
const getAllCoursesByYear = 'https://beta.aminyoussef.com/api/api-selectData.php?tableName=cat&where=class&equalWhat=';
const checkIfTheCourseIsOwned = 'https://beta.aminyoussef.com/api/api-getOwnedCourse.php';
const getCoursesByTeacher = 'https://beta.aminyoussef.com/api/api-selectData.php?tableName=videos&where=pub&equalWhat=';